a = str(input('Digite algo: '))
print('A classe primitiva é: ', type(a))
print('É somente espaço em branco?', a.isspace())
print('É um numero? ', a.isnumeric())
print('É um texto? ', a.isalpha())
print('É um texto ou numero?', a.isalnum())
print('É um texto maiusculo?', a.isupper())
print('É um texto minusculo?', a.islower())
print('Tem maiusculo e minusculo junto?', a.istitle())
